Repository U-Wreckcar/U-wreckcar-BE, pull requests merged in 2023-03, with the labels that each got.

#7 ♻️ 기존 코드 수정 및 구조 설정 & dependency 추가 & 카카오 로그인 추가 #6
  README.md
  app.js
  package-lock.json
  package.json
  src/controllers/authController.js
  src/controllers/user/getUserProfile.js
  src/controllers/user/kakaoLogin.js
  src/dummy.txt
  src/routes/router.js
  src/routes/userRouter.js
  src/routes/utmRouter.js
  utils/middleware.js
Labels: enhancement, fix

#10 :triangular_flag_on_post: 카카오 로그인 기능 추가
  .eslintrc
  app.js
  package-lock.json
  package.json
  src/controllers/user/getUserProfile.js
  src/controllers/user/kakaoLogin.js
  src/routes/userRouter.js
  utils/middleware.js
Labels: enhancement

#11 FEAT : :sparkles: excell 파일로 추출하기 기능 추가
  app.js
  exportDataToExcel.js
  exportDateToPdf.js
  package-lock.json
  package.json
  src/config/dbconfig.js
  src/controllers/utm/exportDataToExcel.js
  src/routes/utmRouter.js
Labels: enhancement

#15 💩 sequelize db:migrate 중 babel version error 상태
  .babelrc
  .eslintignore
  .sequelizerc
  config/config.js
  exportDataToExcel.js
  migrations/20230304194425-create-user.js
  migrations/20230304195122-create-utm.js
  migrations/20230304195310-create-user-utm-medium.js
  migrations/20230304195329-create-user-utm-source.js
  migrations/20230304195523-create-user-utm.js
  models/index.js
  models/user.js
  models/user_utm.js
  models/user_utm_medium.js
  models/user_utm_source.js
  models/utm.js
  package-lock.json
  package.json
  src/config/dbconfig.js
  src/mysql.js
Labels: bug, enhancement

#16 :bug: sequelize migrate 에러 수정 / dependencies 정리
  .sequelizerc
  config/config.js
  migrations/20230304194425-create-user.js
  migrations/20230304195122-create-utm.js
  migrations/20230304195310-create-user-utm-medium.js
  migrations/20230304195329-create-user-utm-source.js
  migrations/20230304195523-create-user-utm.js
  migrations/20230311173559-create-utms.cjs
  migrations/20230311173610-create-users.cjs
  migrations/20230311174828-create-user-utm-sources.cjs
  migrations/20230311175754-create-user-utm-mediums.cjs
  models/index.js
  models/user-utm-mediums.js
  models/user-utm-sources.js
  models/user.js
  models/user_utm.js
  models/user_utm_medium.js
  models/user_utm_source.js
  models/users.js
  models/utm.js
  models/utms.js
  package-lock.json
  package.json
Labels: bug, fix

#17 FEAT : :sparkles: :recycle: UTM 추출하기를 위한 필터링 함수추가 / UTM 메모 수정하기능 추가
  src/config/dbconfig.js
  src/controllers/utm/exportDataToExcel.js
  src/controllers/utm/utmFilter.js
  src/controllers/utm/utmMemo.js
  src/routes/utmRouter.js
Labels: enhancement, fix

#19 🐛 Fix import sequelize model error & fix models configure
  .idea/aws.xml
  .idea/dataSources.xml
  .idea/git_toolbox_prj.xml
  app.js
  config/config.js
  exportDateToPdf.js
  migrations/20230311173559-create-utms.cjs
  migrations/20230311173610-create-users.cjs
  migrations/20230311174828-create-user-utm-sources.cjs
  migrations/20230311175754-create-user-utm-mediums.cjs
  migrations/20230315021142-utms.cjs
  migrations/20230315021521-users.cjs
  migrations/20230315021543-user-utm-mediums.cjs
  migrations/20230315021550-user-utm-sources.cjs
  models/index.js
  models/user-utm-mediums.js
  models/user-utm-sources.js
  models/users.js
  models/utms.js
  src/config/dbconfig.js
  src/controllers/utm/utm-crud.js
  src/modules/sequelize.js
  src/mysql.js
  src/routes/utmRouter.js
Labels: enhancement, fix

#22 :recycle: http & https 배포 환경에 맞게 설정, api 에 authentication 미들웨어 추가
  app.js
  src/routes/userRouter.js
  src/routes/utmRouter.js
Labels: enhancement, fix

#23 :recycle: 서버 테스트 후 불필요한 코드 제거 및 유저 디비 수정
  app.js
  migrations/20230315021521-users.cjs
  models/users.js
  src/controllers/utm/utm-crud.js
  src/modules/user.module.js
  utils/middleware.js
Labels: bug, fix

#24 :recycle: header 설정
  app.js
  src/routes/userRouter.js
  utils/middleware.js
Labels: fix

#25 ♻️ autoIncreament 다시 설정 & cookie 전달. & helmet 설정
  app.js
  migrations/20230315021521-users.cjs
  package-lock.json
  package.json
  src/config/kakaoStrategy.js
  src/modules/user.module.js
  src/routes/userRouter.js
  utils/middleware.js
Labels: fix

#26 ♻️ createUtm 배열로 받아서 생성.
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
  src/routes/userRouter.js
  utils/middleware.js
Labels: fix

#27 ♻️ createUTM 부분 에러처리 수정
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
Labels: fix

#28 ♻️ email 제공 안하고 회원가입 시도 시 login 페이지로 redirect
  utils/middleware.js
Labels: fix

#29 :recycle: 외부 UTM 추가할 때 날짜 입력값으로 데이터 생성하기.
  src/modules/utm.module.js
Labels: fix

#31 ♻️ created_at 'YYYY-MM-DD' 로 변환 & 삭제 로직 변경 & 메모 수정 성현님 PR 반영
  app.js
  migrations/20230315021142-utms.cjs
  src/controllers/utm/utm-crud.js
  src/controllers/utm/utmMemo.js
  src/modules/utm.module.js
  src/routes/utmRouter.js
Labels: bug, fix

#34 :hammer: umt.module.js 추가
  src/modules/utm.module.js
Labels: fix

#36 :bug: 전체 데이터 날짜 수정 & 엔드포인트 수정
  package-lock.json
  package.json
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
  src/routes/userRouter.js
Labels: bug, fix

#40 :bug: 전체 UTM return 수정
  migrations/20230315021142-utms.cjs
  models/utms.js
  src/controllers/utm/utm-crud.js
Labels: fix

#41 🐛 shorten url throw 주석
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
Labels: fix

#46 🚀 프론트 로컬 테스트환경 cors origin 동적 할당
  app.js
Labels: enhancement, fix

#47 :recycle: 빈 값에 null 대신 '-' 입력
  src/modules/utm.module.js
Labels: fix

#50 :zap: rate limiting 추가
  app.js
  package-lock.json
  package.json
  src/modules/utm.module.js
Labels: enhancement

#52 ⚡ shortener 다른 서비스 교체
  package-lock.json
  package.json
  src/modules/utm.module.js
Labels: fix

#60 ♻️ fix order by desc & fix toCSV
  .github/workflows/deploy.yml
  .gitignore
  dist/dummy.txt
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
  src/routes/utmRouter.js
Labels: fix

#61 ♻️ fix make shorten url
  src/controllers/utm/utm-crud.js
  src/modules/utm.module.js
Labels: fix

#65 :sparkles: shortUrl click count return 추가
  app.js
  config/mongo.config.js
  migrations/20230315021142-utms.cjs
  migrations/20230325114718-addcolumn.cjs
  models/utms.js
  package-lock.json
  package.json
  src/config/redis.config.js
  src/controllers/user/companySignup.js
  src/controllers/utm/utm-crud.js
  src/modules/mongo.module.js
  src/modules/utm.module.js
Labels: enhancement

#66 ✨ 자체 회원가입 추가(JWT, authenticate, nodemailer)
  .github/workflows/deploy.yml
  migrations/20230315021521-users.cjs
  migrations/20230325180741-addUserColumns.cjs
  models/users.js
  package-lock.json
  package.json
  src/config/nodemailer.config.js
  src/controllers/user/companySignup.js
  src/modules/jwt.module.js
  src/modules/user.module.js
  src/modules/utm.module.js
  src/routes/userRouter.js
  src/routes/utmRouter.js
  utils/middleware.js
Labels: enhancement
